name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust
      run: |
        if rustup --version >/dev/null 2>&1; then
            rustup update
        else
             curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
             echo ::add-path::$HOME/.cargo/bin
        fi

    - name: Rust version
      run: |
        cargo --version
        rustc --version

    - name: Check code
      run: cargo clippy --features semihosting,log-integration,log-colours,itm
